Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -19,14 +19,14 @@ jobs:
           python-version: '3.9'
 
       - name: Check if auth-service exists
-        run: |
-          if [ ! -f "./devops-microservices-pipeline/services/auth-service/requirements.txt" ]; then
-            echo "Auth service not found."
-            exit 1
-          fi
+  run: |
+    if [ ! -f "./devops-microservices-pipeline/services/auth-service/requirements.txt" ]; then
+      echo "Auth service not found."
+      exit 1
+    fi
 
-      - name: Install Python dependencies
-        working-directory: ./services/auth-service
-        run: |
-          python -m pip install --upgrade pip
-          pip install -r requirements.txt
+- name: Install Python dependencies
+  working-directory: ./devops-microservices-pipeline/services/auth-service
+  run: |
+    python -m pip install --upgrade pip
+    pip install -r requirements.txt
